Imports

In [1]:
import sqlite3
from pathlib import Path

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

Database Connection

In [2]:
ROOT = Path.cwd().parents[1]

DB_PATH = ROOT / "storage" / "database" / "ETH.db"

print(DB_PATH)

conn = sqlite3.connect(DB_PATH)

d:\Projects\myprojets\projects\project_peace\ethereum\eth_bot\storage\database\ETH.db

Load Data

In [3]:
query = """
SELECT *
FROM ohlcv
ORDER BY open_time
"""

df = pd.read_sql(query, conn)

df.head()

,id,exchange,symbol,interval,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_volume,taker_buy_quote_volume,created_at
0,1,Binance,ETHUSDT,1d,1698969600000,1800.79,1834.58,1777.11,1832.71,315000.2678,1699055999999,5.682445e+08,713592,148670.1446,2.682140e+08,2026-07-29 06:26:50
1,2,Binance,ETHUSDT,1d,1699056000000,1832.70,1869.90,1824.03,1855.54,171538.0364,1699142399999,3.155605e+08,463794,90964.8828,1.673829e+08,2026-07-29 06:26:50
2,3,Binance,ETHUSDT,1d,1699142400000,1855.54,1912.67,1846.11,1891.71,383106.7628,1699228799999,7.215084e+08,780672,194760.1848,3.668251e+08,2026-07-29 06:26:50
3,4,Binance,ETHUSDT,1d,1699228800000,1891.71,1914.23,1868.48,1900.95,328746.2394,1699315199999,6.221989e+08,717293,163547.4576,3.095834e+08,2026-07-29 06:26:50
4,5,Binance,ETHUSDT,1d,1699315200000,1900.95,1906.99,1850.32,1885.27,332419.4406,1699401599999,6.255663e+08,760921,157050.0994,2.955991e+08,2026-07-29 06:26:50

Dataset Information

In [4]:
print(df.shape)

df.info()

(1000, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      1000 non-null   int64
 1   exchange                1000 non-null   object
 2   symbol                  1000 non-null   object
 3   interval                1000 non-null   object
 4   open_time               1000 non-null   int64
 5   open                    1000 non-null   float64
 6   high                    1000 non-null   float64
 7   low                     1000 non-null   float64
 8   close                   1000 non-null   float64
 9   volume                  1000 non-null   float64
 10  close_time              1000 non-null   int64
 11  quote_asset_volume      1000 non-null   float64
 12  number_of_trades        1000 non-null   int64
 13  taker_buy_base_volume   1000 non-null   float64
 14  taker_buy_quote_volume  1000 non-null   float64
 15  created_at              1000 non-null   object
dtypes: float64(8), int64(4), object(4)
memory usage: 125.1+ KB

Convert Timestamp

In [5]:
df["open_datetime"] = pd.to_datetime(
    df["open_time"],
    unit="ms",
    utc=True
)

df["close_datetime"] = pd.to_datetime(
    df["close_time"],
    unit="ms",
    utc=True
)

df.head()

,id,exchange,symbol,interval,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_volume,taker_buy_quote_volume,created_at,open_datetime,close_datetime
0,1,Binance,ETHUSDT,1d,1698969600000,1800.79,1834.58,1777.11,1832.71,315000.2678,1699055999999,5.682445e+08,713592,148670.1446,2.682140e+08,2026-07-29 06:26:50,2023-11-03 00:00:00+00:00,2023-11-03 23:59:59.999000+00:00
1,2,Binance,ETHUSDT,1d,1699056000000,1832.70,1869.90,1824.03,1855.54,171538.0364,1699142399999,3.155605e+08,463794,90964.8828,1.673829e+08,2026-07-29 06:26:50,2023-11-04 00:00:00+00:00,2023-11-04 23:59:59.999000+00:00
2,3,Binance,ETHUSDT,1d,1699142400000,1855.54,1912.67,1846.11,1891.71,383106.7628,1699228799999,7.215084e+08,780672,194760.1848,3.668251e+08,2026-07-29 06:26:50,2023-11-05 00:00:00+00:00,2023-11-05 23:59:59.999000+00:00
3,4,Binance,ETHUSDT,1d,1699228800000,1891.71,1914.23,1868.48,1900.95,328746.2394,1699315199999,6.221989e+08,717293,163547.4576,3.095834e+08,2026-07-29 06:26:50,2023-11-06 00:00:00+00:00,2023-11-06 23:59:59.999000+00:00
4,5,Binance,ETHUSDT,1d,1699315200000,1900.95,1906.99,1850.32,1885.27,332419.4406,1699401599999,6.255663e+08,760921,157050.0994,2.955991e+08,2026-07-29 06:26:50,2023-11-07 00:00:00+00:00,2023-11-07 23:59:59.999000+00:00

Set Index

In [ ]:
df.set_index("open_datetime", inplace=True)

df.head()